### ISSUE TITLE
✨ [FEATURE]: Add `markdownlint-cli` to `mirsg-hooks`

### ISSUE THREAD

**Issue by paddyroddy** [UCL-MIRSG/.github#89]
### Feature Description

Following the introduction of `yamllint` in #88, it could be worth adding `markdownlint-fix` from https://github.com/igorshubovych/markdownlint-cli. Much like `yamllint` this will make our `markdown` files better, and potentially easier to maintain. However, like `yamllint`, if we do this then it is very likely that any repo which is using the `mirsg-hooks` will fail linting (as a lot of our `markdown` files are a bit of a mess). So if we do this, let's wait until #88 occurs, which should be ~1st Feb 2024.

For reference https://github.com/paddyroddy/.github/blob/19e037896d2ac64ac06ffe3b984644bcdc98b5a0/precommit/general/general-hooks.yml#L25-L28

### Definition of Done

```[tasklist]
### Related Stories
```

```[tasklist]
### Related Tasks
```

**Comment by paddyroddy** [comment]
Proposal
```yaml
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.38.0
  hooks:
    - id: markdownlint-fix
      args:
        - --disable=MD013
```
tested in UCL-MIRSG/UCLH-MPBE-SRR-XNAT#187
